### ISSUE TITLE
Can't load config files in workspace since vitest 2.1.5

### ISSUE THREAD

**Issue by jpleclerc** [nuxt/test-utils#1034]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  ../../packages/package-one/src/module, ../../packages/package-two/src/module
- Build Modules:    -
------------------------------

### Reproduction

You get the error when using vitest 2.1.8 (the error appears since 2.1.5): https://stackblitz.com/edit/github-n797ja-hxhseq

It works in 2.1.4: https://stackblitz.com/edit/github-n797ja-2rtuvw

### Describe the bug

In a workspace with multiple projects, it is no longer possible to call defineVitestConfig because of unctx conflicts:

```
Error: Context conflict
    at checkConflict (file:///home/projects/github-n797ja-hxhseq/node_modules/unctx/dist/index.mjs:25:13)
    at set (file:///home/projects/github-n797ja-hxhseq/node_modules/unctx/dist/index.mjs:59:22)
    at initNuxt (file:///home/projects/github-n797ja-hxhseq/node_modules/nuxt/dist/index.mjs:4404:21)
    at ready (file:///home/projects/github-n797ja-hxhseq/node_modules/nuxt/dist/index.mjs:4306:26)
    at loadNuxt (file:///home/projects/github-n797ja-hxhseq/node_modules/nuxt/dist/index.mjs:4871:16)
```

Could be related to https://github.com/nuxt/test-utils/issues/537

### Logs

```shell-script

```

**Comment by kleinpetr** [comment]
Same here
