### ISSUE TITLE
Context conflict when running multiple projects with nuxt-vitest

### ISSUE THREAD

**Issue by TECH7Fox** [nuxt/test-utils#537]
I have a monorepo with a nuxt 3 app and multiple nuxt modules. The nuxt 3 app already has nuxt-vitest tests and it works great with the new RootDir option. But when I try to add nuxt-vitest to a module in the monorepo, it fails with this error:
```
> vitest --ui --coverage

failed to load config from /home/jordy/repositories/my_repo/packages/my_package/vitest.config.ts
Error: Context conflict
 ❯ checkConflict node_modules/unctx/dist/index.mjs:6:13
 ❯ Object.set node_modules/unctx/dist/index.mjs:40:9
 ❯ initNuxt node_modules/nuxt/dist/index.mjs:2689:11
 ❯ Object.ready node_modules/nuxt/dist/index.mjs:2680:18
 ❯ loadNuxt node_modules/nuxt/dist/index.mjs:2989:16
 ❯ loadNuxt node_modules/@nuxt/kit/dist/index.mjs:534:19
 ❯ startNuxtAndGetViteConfig node_modules/nuxt-vitest/dist/config.mjs:8:16
 ❯ getVitestConfigFromNuxt node_modules/nuxt-vitest/dist/config.mjs:48:15
```

On their own it works, it's only when running the global vitest workspace, which has all the coverage and UI in one place.

Not sure how to fix this.

**Comment by danielroe** [comment]
@TECH7Fox How are you running your reproduction? What are the steps I should take after cloning it?

**Comment by TECH7Fox** [comment]
@danielroe `npm install` and then `npm test` should do it.

**Comment by linspw** [comment]
@danielroe I believe I understand a little about the situation.

Since the context shares the same "vitest loading", the context [unctx](https://github.com/unjs/unctx) nuxt interprets that they tried to replace the context without unloading the previous one

Maybe a workaround is possible with an "appName" and using unctx's "createNamespace"

```
failed to load config from /home/jesse/Documents/Projects/mp-boot/projects/snown/configs/tests/unit/vitest.unit.config.ts
err
Error: Context conflict
    at checkConflict (file:///home/jesse/Documents/Projects/mp-boot/projects/snown/node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:6:13)
    at Object.set (file:///home/jesse/Documents/Projects/mp-boot/projects/snown/node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:40:9)
    at initNuxt (file:///home/jesse/Documents/Projects/mp-boot/projects/snown/node_modules/.pnpm/nuxt@3.11.2_@types+node@20.12.6_@unocss+reset@0.59.0_axios@1.6.8_eslint@8.57.0_floating-vue@5_7aesqhy3h5e7wnpeolvewurpau/node_modules/nuxt/dist/index.mjs:3933:11)
    at Object.ready (file:///home/jesse/Documents/Projects/mp-boot/projects/snown/node_modules/.pnpm/nuxt@3.11.2_@types+node@20.12.6_@unocss+reset@0.59.0_axios@1.6.8_eslint@8.57.0_floating-vue@5_7aesqhy3h5e7wnpeolvewurpau/node_modules/nuxt/dist/index.mjs:3912:18)
    at loadNuxt (file:///home/jesse/Documents/Projects/mp-boot/projects/snown/node_modules/.pnpm/nuxt@3.11.2_@types+node@20.12.6_@unocss+reset@0.59.0_axios@1.6.8_eslint@8.57.0_floating-vue@5_7aesqhy3h5e7wnpeolvewurpau/node_modules/nuxt/dist/index.mjs:4331:16)
    at async loadNuxt (file:///home/jesse/Documents/Projects/mp-boot/projects/snown/node_modules/.pnpm/@nuxt+kit@3.11.2_rollup@4.14.1/node_modules/@nuxt/kit/dist/index.mjs:2570:19)
    at async startNuxtAndGetViteConfig (file:///home/jesse/Documents/Projects/mp-boot/projects/snown/node_modules/.pnpm/@nuxt+test-utils@3.12.0_@playwright+test@1.43.0_@testing-library+vue@8.0.3_@vitest+ui@1.4.0_@_hrzaxqt55r4hxtaqjvrqu3lzmq/node_modules/@nuxt/test-utils/dist/config.mjs:40:16)
    at async getVitestConfigFromNuxt (file:///home/jesse/Documents/Projects/mp-boot/projects/snown/node_modules/.pnpm/@nuxt+test-utils@3.12.0_@playwright+test@1.43.0_@testing-library+vue@8.0.3_@vitest+ui@1.4.0_@_hrzaxqt55r4hxtaqjvrqu3lzmq/node_modules/@nuxt/test-utils/dist/config.mjs:83:15)
    at async file:///home/jesse/Documents/Projects/mp-boot/projects/snown/node_modules/.pnpm/@nuxt+test-utils@3.12.0_@playwright+test@1.43.0_@testing-library+vue@8.0.3_@vitest+ui@1.4.0_@_hrzaxqt55r4hxtaqjvrqu3lzmq/node_modules/@nuxt/test-utils/dist/config.mjs:198:7
    at async loadConfigFromFile (file:///home/jesse/Documents/Projects/mp-boot/projects/snown/node_modules/.pnpm/vite@5.2.8_@types+node@20.12.6_sass@1.74.1/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:68530:24) {stack: 'Error: Context conflict
    at checkConflict …te/dist/node/chunks/dep-whKeNLxG.js:68530:24)', message: 'Context conflict'}

```

Workspace File:
```ts
import { defineWorkspace } from 'vitest/config'

export default defineWorkspace([
  {
    extends: './configs/tests/e2e/vitest.e2e.config.ts',
    test: {
      name: 'E2E',
    },
  },
  {
    extends: './configs/tests/unit/vitest.unit.config.ts',
    test: {
      name: 'UNIT',
    },
  },
])

```

vitest.e2e.config
```ts
import { defineVitestConfig } from '@nuxt/test-utils/config'

export default defineVitestConfig({
  test: {
    environment: 'nuxt',
    env: {
      NODE_ENV: 'test',
    },
    include: ['**/*.{test,spec}.e2e.?(c|m)[jt]s?(x)'],
  },
})

```
vitest.unit.config
```ts
import { defineVitestConfig } from '@nuxt/test-utils/config'

export default defineVitestConfig({
  test: {
    environment: 'happy-dom',
    env: {
      NODE_ENV: 'test',
    },
    include: ['**/*.{test,spec}.unit.?(c|m)[jt]s?(x)'],
  },
})

```
