### ISSUE TITLE
0.11.3 broken module include

### ISSUE THREAD

**Issue by darvids0n** [nuxt/test-utils#614]
Version: 0.11.3
Does not occur in 0.11.2
It also doesn't occur when pinning `"vitest-environment-nuxt": "0.11.2"` with nuxt-vitest on 0.11.3.

Occurs when running `npx nuxi prepare` after updating to the new package version, but only when there is peer dependency warning for `vitest`. This becomes a permanent error i.e. fixing the peerdep warning on `vitest` doesn't resolve the issue.

To trigger the failure state, set `"vitest": "^0.34.0"` in `package.json`, `npm i` and then set back to `"^0.33.0"` afterwards.

Log:

```log
[4:29:42 PM]  ERROR  Error while requiring module vitest-environment-nuxt/module: Error: Cannot find module '/Users/username/projectFolder/.playground/vitest-environment-nuxt/module'
Require stack:
- /Users/username/projectFolder/index.js


[4:29:42 PM]  ERROR  Cannot find module '/Users/username/projectFolder/.playground/vitest-environment-nuxt/module'
Require stack:
- /Users/username/projectFolder/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
  at Function.resolve (node:internal/modules/cjs/helpers:125:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:251148)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:2239:29)
  at requireModule (node_modules/@nuxt/kit/dist/index.mjs:2244:24)
  at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2472:90)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2438:47)
  at async setup (node_modules/nuxt-vitest/dist/module.mjs:24:5)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2141:17)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2439:95) 



[4:29:42 PM]  ERROR  Cannot find module '/Users/username/projectFolder/.playground/vitest-environment-nuxt/module'
Require stack:
- /Users/username/projectFolder/index.js

npm ERR! code 1
npm ERR! path /Users/username/projectFolder
npm ERR! command failed
npm ERR! command sh -c nuxi prepare .playground

npm ERR! A complete log of this run can be found in: /Users/username/.npm/_logs/2023-11-14T06_29_32_752Z-debug-0.log
```

**Comment by danielroe** [comment]
The issue here was that nuxt-vitest was not compatible with vitest v0.34+. But that has been resolved in the latest nightly release of `@nuxt/test-utils` and the fix will be in the next release.
